services:
  app:
    image: frontend
    build:
      context: ./uusi-front/patientor
      dockerfile: Dockerfile
    volumes:
      - ./uusi-front/patientor/:/usr/src/app
    # ports:
    #   - 5173:5173
    container_name: frontend

  server:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    # ports:
    #   - 3001:3001
    container_name: backend
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server